# Generated by Django 4.1.3 on 2022-11-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='helo', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
